
services:
  debian:
    image: debian
    volumes:
      - ./Makefile:/usr/src/yinit/Makefile:ro
      - ./pyproject.toml:/usr/src/yinit/pyproject.toml:ro
      - ./setup.py:/usr/src/yinit/setup.py:ro
      - ./MANIFEST.in:/usr/src/yinit/MANIFEST.in:ro
      - ./README.md:/usr/src/yinit/README.md:ro
      - ./src/:/usr/src/yinit/src
      - ./targets:/etc/yinit/targets:ro
    command: "sh -c 'apt update && apt install -y python3-build python3-pip python3-venv python-is-python3 make'"
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    working_dir: /usr/src/yinit/
    network_mode: host
    environment:
      DBG_SERVER: "127.0.0.1:5678"
    cap_add: ['ALL']
    devices:
      - /dev/fuse

  alpine:
    image: alpine
    volumes:
      - ./Makefile:/usr/src/yinit/Makefile:ro
      - ./pyproject.toml:/root/pyproject.toml:ro
      - ./setup.py:/usr/src/yinit/setup.py:ro
      - ./MANIFEST.in:/usr/src/yinit/MANIFEST.in:ro
      - ./README.md:/usr/src/yinit/README.md:ro
      - ./src/:/usr/src/yinit/src
      - ./targets:/etc/yinit/targets:ro
    command: "/bin/sh -c 'apk update && apk add cython gcc make musl-dev python3-dev'"
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    working_dir: /usr/src/yinit/
    network_mode: host
    environment:
      DBG_SERVER: "127.0.0.1:5678"
    cap_add: ['ALL']
    devices:
      - /dev/fuse

  sandbox:
    build:
      context: sandbox
    network_mode: host
    environment:
      DBG_SERVER: "127.0.0.1:5678"
    cap_add: ['ALL']
    devices:
      - /dev/fuse
