[build-system]
requires = [
    "setuptools>=68",
    "wheel",
    "cython>=3.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "yinit"
version = "0.1.0"
description = "Unix init system developed in Python"
authors = [{name = "Mateusz Piwek", email = "mp@200ms.net"}]
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

#[tool.setuptools]
#package-dir = {"" = "src"}
#packages = ["yinit"]

